# Installs MATLAB runtime R2016a, the most recent available
# that is compatible with the installation instructions at
# https://www.mathworks.com/help/compiler_sdk/dotnet/install-the-matlab-runtime.html
# Newer version from https://www.mathworks.com/products/compiler/matlab-runtime.html
# are distributed as .dmg files and require a different installation process
name: Install SINGE

on: [push, pull_request]

jobs:
  build:
    # See available macOS software https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-latest
    env:
      SINGE_VERSION: v0.4.1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache MATLAB runtime installer
      id: cache-installer
      uses: actions/cache@v1
      with:
        path: installer
        key: ${{ runner.os }}-matlab-R2016a-installer
    - name: Download MATLAB runtime installer
      if: steps.cache-installer.outputs.cache-hit != 'true'
      run: wget --directory-prefix=installer https://ssd.mathworks.com/supportfiles/downloads/R2016a/deployment_files/R2016a/installers/maci64/MCR_R2016a_maci64_installer.zip
    - name: Install MATLAB runtime
      run: |
        unzip -d . -q installer/MCR_R2016a_maci64_installer.zip
        sudo ./install -mode silent -agreeToLicense yes
        export MATLAB_INSTALL=/Applications/MATLAB/MATLAB_Runtime/v901
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$MATLAB_INSTALL/runtime/maci64:$MATLAB_INSTALL/sys/os/maci64:$MATLAB_INSTALL/bin/maci64
        export PATH=$PATH:$MATLAB_INSTALL/bin/maci64
    - name: Install Glmnet and SINGE
      run: |
        wget http://web.stanford.edu/~hastie/glmnet_matlab/glmnet_matlab.zip
        unzip -q glmnet_matlab.zip
        SINGE_URL=https://github.com/gitter-lab/SINGE/releases/download/$SINGE_VERSION
        wget $SINGE_URL/SINGE_GLG_Test
        chmod u+x SINGE_GLG_Test
        wget $SINGE_URL/SINGE_Aggregate
        chmod u+x SINGE_Aggregate
    - name: Run SINGE
      run: |
        printenv
        bash SINGE.sh $MATLAB_INSTALL standalone data1/X_SCODE_data.mat data1/gene_list.mat Output default_hyperparameters.txt
