# Installs MATLAB runtime R2016a, the most recent available
# that is compatible with the installation instructions at
# https://www.mathworks.com/help/compiler_sdk/dotnet/install-the-matlab-runtime.html
# Newer version from https://www.mathworks.com/products/compiler/matlab-runtime.html
# are distributed as .dmg files and require a different installation process
name: Install SINGE

on: [push, pull_request]

jobs:
  build:
    # See available macOS software https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-latest
    env:
      SINGE_VERSION: v0.4.1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache MATLAB runtime installer
      id: cache-installer
      uses: actions/cache@v1
      with:
        path: installer
        key: ${{ runner.os }}-matlab-R2018a-installer
    - name: Download MATLAB runtime installer
      if: steps.cache-installer.outputs.cache-hit != 'true'
      run: wget --directory-prefix=installer https://ssd.mathworks.com/supportfiles/downloads/R2018a/deployment_files/R2018a/installers/maci64/MCR_R2018a_maci64_installer.dmg.zip
    - name: Test SINGE download
      run: |
        wget --recursive --no-parent https://www.biostat.wisc.edu/~gitter/tmp/mac/
        ls -l
    - name: Install MATLAB runtime
      run: |
        unzip -d . -q installer/MCR_R2018a_maci64_installer.dmg.zip
        hdiutil mount MCR_R2018a_maci64_installer.dmg
        cp -R /Volumes/MCR_R2018a_maci64_installer .
        hdiutil unmount /Volumes/MCR_R2018a_maci64_installer
        sudo ./MCR_R2018a_maci64_installer/InstallForMacOSX.app/Contents/MacOS/InstallForMacOSX -mode silent -agreeToLicense yes
        MATLAB_RUNTIME_PATH=/Applications/MATLAB/MATLAB_Runtime/v94
        echo "::set-env name=MATLAB_RUNTIME_PATH::$MATLAB_RUNTIME_PATH"
        echo "::set-env name=DYLD_LIBRARY_PATH::$MATLAB_RUNTIME_PATH/runtime/maci64:$MATLAB_RUNTIME_PATH/sys/os/maci64:$MATLAB_RUNTIME_PATH/bin/maci64"
        echo "::add-path::$MATLAB_RUNTIME_PATH/bin/maci64"
    - name: Install SINGE
      run: |
        ls
#        SINGE_URL=https://github.com/gitter-lab/SINGE/releases/download/$SINGE_VERSION
#        wget $SINGE_URL/SINGE_GLG_Test
#        chmod u+x SINGE_GLG_Test
#        wget $SINGE_URL/SINGE_Aggregate
#        chmod u+x SINGE_Aggregate
    - name: Run SINGE
      run: |
         ls
#        ls -l
#        file SINGE_GLG_Test
#        #bash SINGE.sh $MATLAB_RUNTIME_PATH standalone data1/X_SCODE_data.mat data1/gene_list.mat Output tests/example_hyperparameters.txt
#        #ls -l Output
