name: Install SINGE

on: [push, pull_request]

jobs:
  build:
    # See available macOS software https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install MATLAB runtime
      run: |
        wget https://ssd.mathworks.com/supportfiles/downloads/R2018a/deployment_files/R2018a/installers/maci64/MCR_R2018a_maci64_installer.dmg.zip
        unzip MCR_R2018a_maci64_installer.dmg.zip
        ./install -mode silent -agreeToLicense yes
