# Installs MATLAB runtime R2020a and tests compiled SINGE for macOS on test data
name: Install test macOS

on: [push, pull_request]

jobs:
  build:
    # See available macOS software https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-latest
    env:
      SINGE_VERSION: v0.4.1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache MATLAB runtime installer
      id: cache-installer
      uses: actions/cache@v1
      with:
        path: installer
        key: ${{ runner.os }}-matlab-R2020a-installer
    - name: Download MATLAB runtime installer
      if: steps.cache-installer.outputs.cache-hit != 'true'
      run: wget --quiet --directory-prefix=installer http://ssd.mathworks.com/supportfiles/downloads/R2020a/Release/2/deployment_files/installer/complete/maci64/MATLAB_Runtime_R2020a_Update_2_maci64.dmg.zip
    - name: Install MATLAB runtime
      run: |
        unzip -d . -q installer/MATLAB_Runtime_R2020a_Update_2_maci64.dmg.zip
        hdiutil mount MATLAB_Runtime_R2020a_Update_2_maci64.dmg
        cp -R /Volumes/MATLAB_Runtime_R2020a_Update_2_maci64 .
        hdiutil unmount /Volumes/MATLAB_Runtime_R2020a_Update_2_maci64
        sudo ./MATLAB_Runtime_R2020a_Update_2_maci64/InstallForMacOSX.app/Contents/MacOS/InstallForMacOSX -mode silent -agreeToLicense yes
        MATLAB_RUNTIME_PATH=/Applications/MATLAB/MATLAB_Runtime/v98
        echo "::set-env name=MATLAB_RUNTIME_PATH::$MATLAB_RUNTIME_PATH"
        echo "::set-env name=DYLD_LIBRARY_PATH::$MATLAB_RUNTIME_PATH/runtime/maci64:$MATLAB_RUNTIME_PATH/sys/os/maci64:$MATLAB_RUNTIME_PATH/bin/maci64"
        echo "::add-path::$MATLAB_RUNTIME_PATH/bin/maci64"
    - name: Install SINGE
      run: |
        wget --quiet https://www.biostat.wisc.edu/~gitter/tmp/mac/SINGE_mac.tgz
        tar -xf SINGE_mac.tgz
        ls -l
#        SINGE_URL=https://github.com/gitter-lab/SINGE/releases/download/$SINGE_VERSION
#        wget $SINGE_URL/SINGE_GLG_Test
#        chmod u+x SINGE_GLG_Test
#        wget $SINGE_URL/SINGE_Aggregate
#        chmod u+x SINGE_Aggregate
    - name: Run SINGE
      run: |
        echo "Running standalone SINGE"
        bash SINGE.sh $MATLAB_RUNTIME_PATH standalone data1/X_SCODE_data.mat data1/gene_list.mat Output tests/example_hyperparameters.txt
        ls -l Output
        cat Output/SINGE_Gene_Influence.txt
